name: Build CloudTruth CLI
description: 'Builds cloudtruth-cli from source'
inputs:
  buildOptions:
    description: Command-line options passed directly to `cargo build`
  testOptions:
    description: Command-line options passed directly to `cargo test`
  ref:
    description: Git ref to build from (defaults to the default branch)
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: '.'
  components:
    description: Rust toolchain components to install (ex rustfmt, clippy)
  target:
    description: Build targets to install with `rustup`. Note you will still need to pass in the `--target` build option with `buildOptions` if you want Cargo to build this target)
  skipUnitTests:
    description: Skips running unit tests
  skipCache:
    description: Skip caching of Cargo registry and dependencies
  skipBuild:
    description: Skip the build step. Useful if you just want to run linting or reports.
  cacheKey:
    description: A custom string to prefix cache keys with when caching build artifacts
    default: v0-cloudtruth-cli
  cacheOnFailure:
    description: "Cache build artifacts even when job fails (default false)"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: cloudtruth/cloudtruth-cli
        ref: ${{ inputs.ref }}
        path: ${{ inputs.path }}

    - uses: Find rust-toolchain file
      shell: bash
      run: |
        if test -f rust-toolchain -o -f rust-toolchain.yml -o -f rust.toolchain-yaml; then
          echo 'Found rust-toolchain file'
        else
          echo 'No rust-toolchain file. Assuming legacy cloudtruth-cli'
          echo RUST_TOOLCHAIN=1.63.0 >> $GITHUB_ENV

    - name: Install Rust
      id: rust
      uses: cloudtruth/rust-toolchain@v1
      with:
        toolchain: ${{ env.RUST_TOOLCHAIN }}
        working-directory: ${{ inputs.path }}
        profile: minimal
        override: true
        components: ${{ inputs.components }}
        target: ${{ inputs.target }}

    - name: Rust Cache
      if: ${{ !inputs.skipCache }}
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: ${{ inputs.cacheKey }}
        shared-key: ${{ runner.os }}
        workspaces: ${{ inputs.path }} -> target
        cache-on-failure: ${{ inputs.cacheOnFailure }}

    - name: Show Rust version and platform details
      working-directory: ${{ inputs.path }}
      shell: bash
      run: rustc --version --verbose

    - name: Cargo Build
      if: ${{ !inputs.skipBuild }}
      working-directory: ${{ inputs.path }}
      shell: bash
      run: cargo build ${{ inputs.buildOptions }}

    - name: Cargo Test
      if: ${{ !inputs.skipBuild && !inputs.skipUnitTests }}
      working-directory: ${{ inputs.path }}
      shell: bash
      run: cargo test ${{ inputs.testOptions }}