name: CI
on: 
  pull_request:
  schedule:
    # Run full test on a nightly basis -- time is GMT, so do it a bit after midnight ET
    - cron: '15 5 * * *' 

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Test Action
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        scenario: [defaults, opts, components, skips, full]

    steps:
      - uses: actions/checkout@v3

      # Scenario: minimal with all defaults.
      # Note: path is required otherwise actions.yml gets overwritten
      # and workflow fails
      - uses: ./
        if: ${{ matrix.scenario == 'defaults' }}
        with:
          path: cloudtruth-cli

      # Scenario: override build/test options
      - uses: ./
        if: ${{ matrix.scenario == 'opts' }}
        with:
          path: cloudtruth-cli
          buildOptions: --release
          testOptions: --no-run -v
      
      # Scenario: install components
      - uses: ./
        if: ${{ matrix.scenario == 'components' }}
        with:
          path: cloudtruth-cli
          components: rustfmt, clippy
        
      # Scenario: using skip options
      - uses: ./
        if: ${{ matrix.scenario == 'skips' }}
        with:
          path: cloudtruth-cli
          skipCache: true
          skipUnitTests: true
          skipBuild: true
      
      # Scenario: all non-skip options except target
      - uses: ./
        if: ${{ matrix.scenario == 'full' }}
        with:
          buildOptions: --release
          testOptions: --release --no-fail-fast
          ref: main
          path: cloudtruth-cli
          components: rustfmt, clippy
          cacheKey: v0-cloudtruth-cli-custom-key
          cacheOnFailure: true


