name: CI
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Run full test on a nightly basis -- time is GMT, so do it a bit after midnight ET
    - cron: '15 5 * * *' 

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Test Action
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        scenario: [defaults, opts, components, legacy-ref, binstall, skips, full]
        include:
          # linux-specific tests
          - { os: ubuntu-latest, scenario: cross}
          - { os: ubuntu-latest, scenario: cross-binstall}

    steps:
      - uses: actions/checkout@v3

      # Scenario: minimal with all defaults.
      # Note: path is required otherwise actions.yml gets overwritten
      # and workflow fails
      - uses: ./
        if: ${{ matrix.scenario == 'defaults' }}
        with:
          path: cloudtruth-cli

      # Scenario: override build/test options
      - uses: ./
        if: ${{ matrix.scenario == 'opts' }}
        with:
          path: cloudtruth-cli
          buildOptions: --release
          testOptions: --no-run -v
      
      # Scenario: install components and profile
      - uses: ./
        if: ${{ matrix.scenario == 'components' }}
        with:
          path: cloudtruth-cli
          profile: default
          components: rustfmt, clippy

      # Scenario: install CLI version with no rust-toolchain file
      - uses: ./
        if: ${{ matrix.scenario == 'legacy-ref' }}
        with:
          path: cloudtruth-cli
          ref: refs/tags/1.1.8
          components: rustfmt, clippy
        
      # Scenario: using skip options
      - uses: ./
        if: ${{ matrix.scenario == 'skips' }}
        with:
          path: cloudtruth-cli
          skipCache: true
          skipUnitTests: true
          skipBuild: true

      - uses: ./
        if: ${{ matrix.scenario == 'binstall' }}
        with:
          path: cloudtruth-cli
          cargoBinstall: true

      - uses: ./
        if: ${{ matrix.scenario == 'cross' }}
        with:
          path: cloudtruth-cli
          cross: true
          target: x86_64-unknown-linux-musl

      - uses: ./
        if: ${{ matrix.scenario == 'cross-binstall' }}
        with:
          path: cloudtruth-cli
          cross: true
          cargoBinstall: true
          target: x86_64-unknown-linux-musl
          editCargoVersion: 0.1.abcde
      
      # Scenario: all non-skip options except target/cross/binstall
      - uses: ./
        if: ${{ matrix.scenario == 'full' }}
        with:
          buildOptions: --release
          testOptions: --release --no-fail-fast
          ref: main
          path: cloudtruth-cli
          components: rustfmt, clippy
          profile: minimal
          override: true
          cacheKey: v0-cloudtruth-cli-custom-key
          cacheDirectories: ${{ env.HOME }}/.cargo/bin
          editCargoVersion: 0.1.abcde


